version: 2
updates:
- package-ecosystem: dotnet-sdk
  directory: "/"
  schedule:
    interval: daily
  groups:
    dotnet-dependencies:
      patterns:
        - "*"
  labels:
    - dependencies
    - dotnet
- package-ecosystem: devcontainers
  directory: "/"
  schedule:
    interval: daily
  groups:
    infrastructure:
      patterns:
        - "*"
  labels:
    - dependencies
    - infrastructure
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  groups:
    infrastructure:
      patterns:
        - "*"
  labels:
    - dependencies
    - infrastructure
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  groups:
    dotnet-dependencies:
      patterns:
        - "*"
  labels:
    - dependencies
    - dotnet
- package-ecosystem: npm
  directory: "/src/RazorPagesProject"
  schedule:
    interval: daily
  groups:
    frontend-dependencies:
      patterns:
        - "*"
  labels:
    - dependencies
    - frontend
