name: "Copilot Setup Steps"

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'

    - name: Install npm dependencies for client-side libraries
      working-directory: ./src/RazorPagesProject
      run: npm install

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Build
      run: dotnet build

    - name: Setup Japanese Font Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          fonts-noto-cjk \
          fonts-noto-cjk-extra \
          fonts-liberation \
          fonts-dejavu-core \
          fontconfig
        # フォントキャッシュを更新
        sudo fc-cache -fv
        # 利用可能な日本語フォントを確認
        fc-list :lang=ja | head -10
