name: Docker Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t dotnet-test-demo:latest .

    - name: Test Docker image
      run: |
        docker run -d --name test-app -p 8080:8080 dotnet-test-demo:latest
        sleep 10
        curl -f http://localhost:8080 || exit 1
        docker stop test-app
        docker rm test-app